config/routes.rb
Pollster::Application.routes.draw do

  get "responses/show"

  get "responses/index"

  get "responses/new"

  get "responses/edit"

  get "responses/update"

  get "responses/destroy"

resources :polls do
  resources :questions
end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer, :poll_id, :question_id

  belongs_to :question

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :edit_url, :name, :poll_url, :id

  has_many :questions
  has_many :answers, :through => :questions
  has_many :responses, :through => :questions

  before_create :generate_edit_url


  def generate_edit_url
    self.edit_url = SecureRandom.urlsafe_base64
  end

  def self.find(input)
    if input.to_i !=0
      super
    else
      find_by_edit_url(input)
    end #end if
  end #end find

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :poll_id, :question, :id

  belongs_to :poll
  has_many :answers
  has_many :responses

end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :question_id, :response
  
  belongs_to :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController


  def index
    @polls = Poll.all
  end

  def create
    @poll = Poll.new(params[:poll])
    
    if @poll.save
      redirect_to poll_path(@poll.id), :notice => "Your url to edit this poll is polls/#{@poll.edit_url}"
    end
  end

  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def edit
  end

  def show
    @poll = Poll.find(params[:id])
    @question = Question.new
    @questions = Question.all

    respond_to do |format|
      format.html
      format.json { render json: @poll}
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params[:question])
    @question.poll_id = params[:poll_id]
    @question.save
    @poll = Poll.find(@question.poll.id)

    redirect_to poll_path(@poll.id)
  end

  def edit
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:id])
  end

  def update
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:id])

  respond_to do |format|
    if @question.update_attributes(params[:question])
        format.html {redirect_to @poll, notice: "Question was updated."}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end #end if
    end #end respond
  end #end update

  def destroy
    @poll = Poll.find(params[:poll_id])
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to poll_path(@poll) }
      format.json { head :no_content }
    end

  end

end #end QuestionsController

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def show
  end

  def index
    @polls = Poll.all
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  

  
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <p>
  <%= link_to "Home", polls_path %></p>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/-form.html.erb
<%= form_for (@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polls/create.html.erb
<h1>Polls#create</h1>
<p>Find me in app/views/polls/create.html.erb</p>

app/views/polls/destroy.html.erb
<h1>Polls#destroy</h1>
<p>Find me in app/views/polls/destroy.html.erb</p>

app/views/polls/edit.html.erb
<h1>Edit your poll</h1>
<p>Find me in app/views/polls/edit.html.erb</p>

app/views/polls/index.html.erb
<h1>Pollster</h1>
<h2>Polls</h2>
<table>
  <tr>
    <th>Polls</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @polls.each do |poll| %>
<tr>
  <td><%= link_to poll.name, poll_path("#{poll.edit_url}") %>

</tr>
<% end %>

</table>


<p>Create a poll!
    <%= button_to "Create Poll", new_poll_path %> </p>

app/views/polls/new.html.erb
<h1>Create A New Poll</h1>
<p>What's the name of your poll?
    <%= form_for(@poll) do |f| %>
    <% if @poll.errors.any? %>
       <div id="error_explanation">
         <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this link from being saved:</h2>

         <ul>
         <% @poll.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
         </ul>
       </div>
     <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name%>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

</p>

app/views/polls/show.html.erb
<h1>Pollster</h1>
<h2>Poll:
  <%= @poll.name %> </h2>
<p id="notice"><%= notice %></p>

<p>
<table>
  <tr>
    <th>Questions</th>
  </tr>

  <% @poll.questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= link_to "Edit", edit_poll_question_path(@poll, question) %></td>
      <td><%= link_to "Delete", poll_question_path(@poll, question), :method => :delete %>
    </tr>

  <% end %>

</table>
</p>

<p>
  <%= render :partial => "questions/questions" %>
</p>


<p>
  Send this link out to the users of your poll:
  <%= "/polls/#{@poll.id}" %>

</p>

app/views/polls/update.html.erb
<h1>Polls#update</h1>
<p>Find me in app/views/polls/update.html.erb</p>

app/views/questions/_questions.html.erb
<br><br>
  <%= form_for [@poll, @question] do |f| %>

    <div class="field">
      <%= f.label :question %><br>
      <%= f.text_field :question %>
    </div>

    <div class="actions">
      <%= f.submit%>
    </div>
  <% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<p>
  <%= render :partial => "questions" %>
</p>

app/views/questions/new.html.erb
<p>
  <%= render :partial => "questions/questions" %>
</p>

app/views/responses/destroy.html.erb
<h1>Responses#destroy</h1>
<p>Find me in app/views/responses/destroy.html.erb</p>

app/views/responses/edit.html.erb
<h1>Responses#edit</h1>
<p>Find me in app/views/responses/edit.html.erb</p>

app/views/responses/index.html.erb
<h1>Pollster</h1>
<h2>Polls</h2>
<p>Click on a poll to take it</p>
<table>
  <tr>
    <th>Polls</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @polls.each do |poll| %>
<tr>
  <td><%= link_to poll.name, poll_path("#{poll.edit_url}") %>

</tr>
<% end %>

</table>


<p>Create a poll!
    <%= button_to "Create Poll", new_poll_path %> </p>

app/views/responses/new.html.erb
<h1>Responses#new</h1>
<p>Find me in app/views/responses/new.html.erb</p>

app/views/responses/show.html.erb
<h1>Responses#show</h1>
<p>Find me in app/views/responses/show.html.erb</p>

app/views/responses/update.html.erb
<h1>Responses#update</h1>
<p>Find me in app/views/responses/update.html.erb</p>